module.exports = {
    addresses: [["BITCOIN", ["BTC"]], ["LITECOIN", ["LTC"]], ["ETHEREUM", ["ETH"]], ["ETHEREUMC", ["ETC"]], ["TETHERUSO", ["UST"]], ["ZCASH", ["ZEC"]], ["MONERO", ["XMR"]], ["IOTA", ["IOT"]], ["RIPPLE", ["XRP"]], ["DASH", ["DSH"]], ["WIRE", ["USD", "GBP", "HKD", "EUR", "SGD", "TWD", "CHF", "JPY", "CNH"]], ["EOS", ["EOS"]], ["SANTIMENT", ["SAN"]], ["OMISEGO", ["OMG"]], ["NEO", ["NEO"]], ["METAVERSE", ["ETP"]], ["QTUM", ["QTM"]], ["EIDOO", ["EDO"]], ["DATACOIN", ["DAT"]], ["TETHERUSE", ["UST"]], ["BGOLD", ["BTG"]], ["QASH", ["QSH"]], ["GOLEM", ["GNT"]], ["STATUS", ["SNT"]], ["TETHEREUE", ["EUT"]], ["BAT", ["BAT"]], ["MNA", ["MNA"]], ["FUN", ["FUN"]], ["ZRX", ["ZRX"]], ["TRX", ["TRX"]], ["SNG", ["SNG"]], ["REP", ["REP"]], ["NEC", ["NEC"]], ["REQ", ["REQ"]], ["LRC", ["LRC"]], ["WAX", ["WAX"]], ["DAI", ["DAI"]], ["BFT", ["BFT"]], ["ODE", ["ODE"]], ["ANT", ["ANT"]], ["STJ", ["STJ"]], ["XLM", ["XLM"]], ["XVG", ["XVG"]], ["MKR", ["MKR"]], ["KNC", ["KNC"]], ["LYM", ["LYM"]], ["UTK", ["UTK"]], ["VEE", ["VEE"]], ["ORS", ["ORS"]], ["ZCN", ["ZCN"]], ["ESS", ["ESS"]], ["ATD", ["ATD"]], ["ADD", ["ADD"]], ["MTO", ["MTO"]], ["IQX", ["IQX"]], ["ZIL", ["ZIL"]], ["BNT", ["BNT"]], ["XRA", ["XRA"]], ["VET", ["VET"]], ["GOT", ["GOT"]], ["XTZ", ["XTZ"]], ["YGG", ["YGG"]], ["MLN", ["MLN"]], ["OMN", ["OMN"]], ["PNK", ["PNK"]], ["DGB", ["DGB"]], ["BSV", ["BSV"]], ["ENJ", ["ENJ"]], ["RBT", ["RBT"]], ["UDC", ["UDC"]], ["TSD", ["TSD"]], ["PAX", ["PAX"]], ["PAS", ["PAS"]], ["VSY", ["VSY"]], ["BTT", ["BTT"]], ["CLO", ["CLO"]], ["GNO", ["GNO"]], ["ATO", ["ATO"]], ["WBT", ["WBT"]], ["XCH", ["XCH"]], ["EUS", ["EUS"]], ["LBT", ["LBT"]], ["LET", ["LET"]], ["LES", ["LES"]], ["GTX", ["GTX"]], ["KAN", ["KAN"]], ["AMP", ["AMP"]], ["ALG", ["ALG"]], ["DUSK", ["DUSK"]], ["UOS", ["UOS"]], ["TETHERUSX", ["UST"]], ["TETHERUSL", ["UST"]], ["RRB", ["RRB"]], ["TETHERUSS", ["UST"]], ["FTT", ["FTT"]], ["TETHERCNHTE", ["CNHT"]], ["CHZ", ["CHZ"]], ["LNX", ["LNX"]], ["TETHERXAUTE", ["XAUT"]], ["TETHERUSDTALG", ["UST"]], ["TETHERUSDTBCH", ["UST"]], ["RINGX", ["RINGX"]], ["BTSE", ["BTSE"]], ["DOG", ["DOG"]], ["DOT", ["DOT"]], ["ADA", ["ADA"]], ["FET", ["FET"]], ["TETHERUSDTOMG", ["UST"]], ["LINK", ["LINK"]], ["COMP", ["COMP"]], ["KSM", ["KSM"]], ["EGLD", ["EGLD"]], ["UNI", ["UNI"]], ["BAND", ["BAND"]], ["AVAX", ["AVAX"]], ["SNX", ["SNX"]], ["YFI", ["YFI"]], ["BAL", ["BAL"]], ["PBTCEOS", ["PBTCEOS"]], ["EOSDT", ["EOSDT"]], ["PLTCEOS", ["PLTCEOS"]], ["PETHEOS", ["PETHEOS"]], ["FIL", ["FIL"]], ["PBTCETH", ["PBTCETH"]], ["PEOSETH", ["PEOSETH"]], ["PLTCETH", ["PLTCETH"]], ["PPNTEOS", ["PPNTEOS"]], ["PLINKEOS", ["PLINKEOS"]], ["PMKREOS", ["PMKREOS"]], ["PYFIEOS", ["PYFIEOS"]], ["JST", ["JST"]], ["HEZ", ["HEZ"]], ["BCHABC", ["BCHABC"]], ["BCHN", ["BCHN"]], ["XDC", ["XDC"]], ["PLU", ["PLU"]], ["SUN", ["SUN"]], ["PUNIEOS", ["PUNIEOS"]], ["PBANDEOS", ["PBANDEOS"]], ["PBALEOS", ["PBALEOS"]], ["PCOMPEOS", ["PCOMPEOS"]], ["PSNXEOS", ["PSNXEOS"]], ["UOP", ["UOP"]], ["POMGEOS", ["POMGEOS"]], ["PANTEOS", ["PANTEOS"]], ["PDAIEOS", ["PDAIEOS"]], ["PLRCEOS", ["PLRCEOS"]], ["B21X", ["B21X"]], ["PUOSEOS", ["PUOSEOS"]], ["PBATEOS", ["PBATEOS"]], ["PREPEOS", ["PREPEOS"]], ["PZRXEOS", ["PZRXEOS"]], ["PPNKEOS", ["PPNKEOS"]], ["SUSHI", ["SUSHI"]], ["XSN", ["XSN"]], ["EXRD", ["EXRD"]], ["AAVE", ["AAVE"]], ["CTK", ["CTK"]], ["SOL", ["SOL"]], ["BEST", ["BEST"]], ["TETHERUSDTSOL", ["UST"]], ["ALBT", ["ALBT"]], ["CEL", ["CEL"]], ["SUKU", ["SUKU"]], ["BMI", ["BMI"]], ["MOB", ["MOB"]], ["NEAR", ["NEAR"]], ["BOSON", ["BOSON"]], ["LUNA", ["LUNA"]], ["TETHERUSDTHEZ", ["UST"]], ["ICE", ["ICE"]], ["DOGE", ["DOGE"]], ["OXY", ["OXY"]], ["1INCH", ["1INCH"]], ["IDX", ["IDX"]], ["FORTH", ["FORTH"]], ["CHEX", ["CHEX"]], ["QTF", ["QTF"]], ["OCEAN", ["OCEAN"]], ["PLANETS", ["PLANETS"]], ["FTM", ["FTM"]], ["NEXO", ["NEXO"]], ["VELO", ["VELO"]], ["ICP", ["ICP"]], ["FCL", ["FCL"]], ["TERRAUST", ["TERRAUST"]], ["MIR", ["MIR"]], ["GRT", ["GRT"]], ["WAVES", ["WAVES"]], ["REEF", ["REEF"]], ["DCR", ["DCR"]], ["CHSB", ["CHSB"]], ["XRD", ["XRD"]], ["EXO", ["EXO"]], ["ROSE", ["ROSE"]], ["MATIC", ["MATIC"]], ["AXS", ["AXS"]], ["HMT", ["HMT"]], ["TETHERUSDTDVF", ["UST", "USDTDVF"]], ["DORA", ["DORA"]], ["JASMY", ["JASMY"]], ["ANC", ["ANC"]], ["AIX", ["AIX"]], ["SHIB", ["SHIB"]], ["MIM", ["MIM"]], ["QRDO", ["QRDO"]], ["TETHERUSDTAVAX", ["UST"]], ["TLOS", ["TLOS"]], ["BOBA", ["BOBA"]], ["SPELL", ["SPELL"]], ["WNCG", ["WNCG"]], ["SRM", ["SRM"]], ["CRV", ["CRV"]], ["THETA", ["THETA"]], ["ZMT", ["ZMT"]], ["WILD", ["WILD"]]],
    addressdata:{
        BTC: { displayName: 'BTC'},
        BCH: { displayName: 'BCH'},
        EOS: { displayName: 'EOS'},
        LTC: { displayName: 'LTC'},
        ETC: { displayName: 'ETC'},
        ZEC: { displayName: 'ZEC'},
        IOTA: { displayName: 'IOTA'},
        QTUM: { displayName: 'QTUM'},
        ONT: { displayName: 'ONT'},
        ZEN: { displayName: 'ZEN'},
        XTZ: { displayName: 'XTZ'},
        ALGO: { displayName: 'ALGO'},
        DOT: { displayName: 'DOT'},
        GRT: { displayName: 'ERC20'},
        AVAX: { displayName: 'AVAX'},
        HBAR: { displayName: 'HBAR'},
        FIL: { displayName: 'FIL'},
        MATIC: { displayName: 'MATIC'},
        USDT: { displayName: 'ERC20'},
        JST: { displayName: 'TRC20'},
        SUN: { displayName: 'TRC20'},
        RSR: { displayName: 'ERC20'},
        LIT: { displayName: 'ERC20'},
        SXP: { displayName: 'ERC20'},
        '1INCH': { displayName: 'ERC20'},
        OMG: { displayName: 'ERC20'},
        BAT: { displayName: 'ERC20'},
        MANA: { displayName: 'ERC20'},
        HOT: { displayName: 'ERC20'},
        AKRO: { displayName: 'ERC20'},
        ANT: { displayName: 'ERC20'},
        CRV: { displayName: 'ERC20'},
        COMP: { displayName: 'ERC20'},
        YFII: { displayName: 'ERC20'},
        YFI: { displayName: 'ERC20'},
        AAVE: { displayName: 'ERC20'},
        REEF: { displayName: 'ERC20'},
        SUSHI: { displayName: 'ERC20'},
        USDC: { displayName: 'ERC20'},
        ETH: { displayName: 'ETH'},
        XRP: { displayName: 'XRP'},
        ADA: { displayName: 'ADA'},
        TRX: { displayName: 'TRX'},
        DOGE: { displayName: 'DOGE'},
        DAI: { displayName: 'DAI'},
        SOL: { displayName: 'SOL'},
        EUR: { displayName: 'EUR'},
        WBTC: { displayName: 'WBTC'},
        UNI: { displayName: 'ERC20'},
        SHIB: { displayName: 'ERC20'},
        BNB: { displayName: 'BEP20BNB'},
    }
}

